const translates = {
	"xjzh_huoying_mingren":"漩涡鸣人",
	"xjzh_huoying_liudaomingren":"六道鸣人",
	"xjzh_huoying_zuozhu":"宇智波佐助",
	"xjzh_huoying_liudaozuozhu":"六道佐助",
	"xjzh_huoying_liudaomingrenfs":"影分身",
	"xjzh_huoying_dou":"药师兜",
	"xjzh_huoying_kakaxi":"旗木卡卡西",
	"xjzh_huoying_zhishui":"宇智波止水",

	"xjzh_huoying_fenshen":"分身",
	"xjzh_huoying_fenshen_info":"<b><font color=orange>〖影分身之术〗</font><b>出牌阶段，你可以与一名角色拼点，若你赢，你可以再次发动该技能且本回合选择目标+1（最多为3），然后你选择摸两张牌或回复一点体力",
	"xjzh_huoying_luoxuan":"螺旋",
	"xjzh_huoying_luoxuan_info":"<b><font color=orange>〖螺旋手里剑〗</font><b>出牌阶段限一次，你可以将一张牌当做任意一张普通锦囊牌使用。",
	"xjzh_huoying_xianshu":"仙术",
	"xjzh_huoying_xianshu_info":"<b><font color=orange>〖仙人模式〗</font><b>游戏开始时，你获得3个仙术查克拉，之后每隔3分钟获得一个仙术查克拉，至多3个，当你失去最后一张手牌时，你可以消耗一个仙术查克拉，将手牌补至体力上限。",
	"xjzh_huoying_zuidun":"嘴遁",
	"xjzh_huoying_zuidun_info":"<b><font color=orange>〖最强嘴遁〗</font><b>限定技，每局游戏限2次，当一名角色濒死时，若你与其均不为主公，你可以令其选择一项：1、将所有牌交给你，然后立即阵亡；2、改变身份/势力与你一致。技能结算后，若其未阵亡，其失去一点体力上限并回复体力至体力上限，然后你与其各摸x张牌（x为其体力值）（限身份模式和国战模式）",
	"xjzh_huoying_kaigua":"开挂",
	"xjzh_huoying_kaigua_info":"<b><font color=orange>〖开挂封号〗</font><b>觉醒技，当你濒死时，你使用自己的外挂并进入〖六道模式〗<br><br><b><font color=orange>〖六道模式〗</font><b>你将你的的体力上限改为为3并回复体力至体力上限，然后重置武将牌和判定区，技能结算后，你失去技能〖分身〗、〖嘴遁〗、〖开挂〗，获得技能〖螺旋手里剑〗、〖阴阳遁术〗、〖多重·影分身之术〗。",
	"xjzh_huoying_dunshu":"遁术",
	"xjzh_huoying_dunshu_info":"<b><font color=orange>〖阳遁术〗</font><b>你的回合外，你防止所有伤害和体力流失然后摸等量牌，然后你可以令等量名角色各回复一点体力，你无法被翻面、横置，且判定效果反转；<br><b><font color=orange>〖阴遁术〗</font><b>你的回合内，场上其他角色所有技能失效，你使用牌无次数限制且你造成的伤害+x(x为你本回合造成伤害的次数)。",
	"xjzh_huoying_liudaofenshen":"分身",
	"xjzh_huoying_liudaofenshen_info":"<b><font color=orange>〖多重·影分身之术〗</font><b>结束阶段，你可以失去一点体力并召唤一个分身代替你的本体存于场上直到其阵亡或你的回合开始，你的本体获得分身的所有手牌（该分身拥有3点体力、3张手牌和技能〖遁术〗）",
	"xjzh_huoying_liudaofenshen2":"分身",
	"xjzh_huoying_qiling":"麒麟",
	"xjzh_huoying_qiling_info":"<b><font color=orange>〖雷遁·麒麟〗</font><b>锁定技，你使用红色牌造成伤害均视为火焰伤害，你使用黑色牌造成伤害均视为雷电伤害，当你至少造成3点火焰伤害和1点雷电伤害后，你可以指定一名不为你的角色，令其受到x点雷电伤害(x为你与其体力差，至少为1)",
	"xjzh_huoying_qiling_huo":"火遁",
	"xjzh_huoying_qiling_lei":"雷遁",
	"xjzh_huoying_qianniao":"千鸟",
	"xjzh_huoying_qianniao_info":"<b><font color=orange>〖雷遁·千鸟〗</font><b>你的回合开始及结束时，你可以视为对一名你攻击范围内的一名其他角色使用一张颜色随机的【杀】，此【杀】不计入出牌次数，若其闪避了此杀，你摸一张牌，你因此技能造成伤害获得一个“瞳”标记。",
	"xjzh_huoying_liudao":"六道",
	"xjzh_huoying_liudao_info":"<b><font color=orange>〖六道模式〗</font><b>觉醒技，当你至少拥有4个“瞳”标记时，你进入重置武将牌并将体力值和体力上限改为3，然后回复体力至体力上限，并获得技能〖瞳术〗，此后你的〖雷遁·千鸟〗被闪避时摸2张牌、〖雷遁·麒麟〗的伤害基数改为2",
	"xjzh_huoying_tongshu":"瞳术",
	"xjzh_huoying_tongshu_info":"<b><font color=orange>〖天手力〗</font><b>当一名角色受到来源不为你伤害时，你可以与其交换位置，并视为对伤害来源使用一张颜色随机且不计入次数的【杀】，若此杀造成伤害，你令其防止此伤害，否则你代替其受到此伤害，你以此法造成的伤害+1；你计算与其他角色距离始终为1。",
	"xjzh_huoying_xianzhang":"仙掌",
	"xjzh_huoying_xianzhang_info":"<b><font color=orange>〖掌仙术〗</font><b>转换技<br><li>阴：每回合限一次，你使用非[伤害]卡牌指定目标后，其可以摸两张牌或回复一点体力；<br><li>阳:每回合限一次，其他角色使用[伤害]卡牌指定你为目标时，你可以扣置一张[伤害]卡牌，其猜测此牌牌名，若错，你可以移除此牌的一个目标。",
	"xjzh_huoying_sihun":"死魂",
	"xjzh_huoying_sihun_info":"<b><font color=orange>〖死魂之术〗</font>限定技，当你濒死时，若场上有已阵亡的角色，你回复x点体力然后摸x张牌，然后令其中随机一个角色复活，复活后其失去所有技能并改变身份、势力与你一致，其拥有2点体力且无法使用、打出牌(x为场上已阵亡的角色数量)。",
	"xjzh_huoying_chuanyi":"传异",
	"xjzh_huoying_chuanyi_info":"<b><font color=orange>〖仙法·传异远影〗</font>当你击败一名角色后，你可以弃置x+1张牌获得其武将牌上的一个技能(x为1，每当你以此技能获得技能后，该数字+1)",
	"xjzh_huoying_kaobei":"拷贝",
	"xjzh_huoying_kaobei_info":"<b><font color=orange>〖复制忍术〗</font>每回合限一次，其他角色发动技能后，若你有“雷”且该技能符合条件，你可以弃置一张“雷”于合适的时机发动一次相应的技能。",
	"xjzh_huoying_shenwei":"神威",
	"xjzh_huoying_shenwei_info":"<b><font color=orange>〖神威〗</font>游戏开始时，你观看牌堆顶7张牌，并将其中4张置于武将牌上称为“雷”；一轮游戏开始时，若当前轮数为奇数，你获得牌堆随机4张牌；当你濒死时，你可以弃置所有“雷”并选择一名角色，然后你选择执行：1，其获得所有“雷”；2，其需弃置任意张点数不小于“雷”的牌，不足则全弃，否则其失去所有体力。",
	"xjzh_huoying_leiqie":"雷切",
	"xjzh_huoying_leiqie_info":"<b><font color=orange>〖雷切〗</font>出牌阶段限一次，你可以交换“雷”和手牌中的任意张牌，然后对一名角色造成1点雷属性伤害。",
	"xjzh_huoying_bietian":"别天",
	"xjzh_huoying_bietian_info":"<b><font color=orange>〖别天神〗</font>当你造成不小于2的伤害后，你可以失去一点体力上限随机偷取目标一个回合阶段；锁定技，你每有一个偷取的额外阶段，你的回合摸牌数+1，若你有额外的阶段，你的回合阶段顺序随机执行。",
	"xjzh_huoying_shunshen":"瞬身",
	"xjzh_huoying_shunshen_info":"<b><font color=orange>〖瞬身术〗</font>锁定技，你的回合开始时，你与一名随机角色交换位置，然后你可以选择使用一张手牌；你防止上家/下家对你造成的伤害。",
	"xjzh_huoying_xuzuo":"须佐",
	"xjzh_huoying_xuzuo_info":"<b><font color=orange>〖须佐能乎〗</font>锁定技，你每发动一次〖瞬身〗与其他角色交换位置获得一点护甲；当你受到伤害时，若你的护甲不小于2，你移除所有护甲，然后获得x/2点体力上限（向下取整）。",

};

export default translates;