import { lib, game, ui, get, ai, _status } from "../../../../../../noname.js";

let Group = function (str1, str2) {
	if (!str2) return str1;
	if (get.mode() == "xjzh_challenge") return str1;
	return game.getExtensionConfig("仙家之魂", "xjzh_changeGroup") ? str2 : str1;
};

const characters = {
	"xjzh_boss_zhangjiao": {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["xjzh_boss_dianxing", "xjzh_boss_leiji", "xjzh_boss_qingling"],
		names: "张|角",
		rank: "legend",
		isUnseen: true,
		isAiForbidden: true,
	},

	//普通BOSS随从
	"xjzh_boss_hjbingyong": {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["xjzh_boss_fubing"],
		names: "null|null",
		rank: "legend",
		isBossAllowed: true,
		isHiddenBoss: true,
		isUnseen: true,
		isAiForbidden: true,
	},
	"xjzh_boss_hjlishi": {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["xjzh_boss_fuli"],
		names: "null|null",
		rank: "legend",
		isBossAllowed: true,
		isHiddenBoss: true,
		isUnseen: true,
		isAiForbidden: true,
	},
	"xjzh_boss_hjshushi": {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["xjzh_boss_fushui"],
		names: "null|null",
		rank: "legend",
		isBossAllowed: true,
		isHiddenBoss: true,
		isUnseen: true,
		isAiForbidden: true,
	},
	"xjzh_boss_hjfangshi": {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["xjzh_boss_fuhuo"],
		names: "null|null",
		rank: "legend",
		isBossAllowed: true,
		isHiddenBoss: true,
		isUnseen: true,
		isAiForbidden: true,
	},
	"xjzh_boss_hjguishi": {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["xjzh_boss_guishu"],
		names: "null|null",
		rank: "legend",
		isBossAllowed: true,
		isHiddenBoss: true,
		isUnseen: true,
		isAiForbidden: true,
	},

	//升华BOSS
	"xjzh_boss_geligaoli": {
		sex: "male",
		group: "shen",
		hp: 15,
		skills: ["xjzh_boss_material", "xjzh_boss_dianmao", "xjzh_boss_dianchong", "xjzh_boss_dianhua"],
		names: "null|null",
		rank: "legend",
		isUnseen: true,
		isAiForbidden: true,
	},
	"xjzh_boss_duruier": {
		sex: "male",
		group: "shen",
		hp: 18,
		skills: ["xjzh_boss_material", "xjzh_boss_mengdu", "xjzh_boss_huanshen"],
		names: "null|null",
		rank: "legend",
		isUnseen: true,
		isAiForbidden: true,
	},
	"xjzh_boss_qier": {
		sex: "male",
		group: "shen",
		hp: 6,
		skills: ["xjzh_boss_material", "xjzh_boss_fusu", "xjzh_boss_ganran", "xjzh_boss_xuezhou"],
		names: "null|null",
		rank: "legend",
		isUnseen: true,
		isAiForbidden: true,
	},
	"xjzh_boss_bingchuanjushou": {
		sex: "male",
		group: "shen",
		hp: 12,
		skills: ["xjzh_boss_material", "xjzh_qishu_shouyu", "xjzh_qishu_shendong", "xjzh_qishu_feimou"],
		names: "null|null",
		rank: "legend",
		isUnseen: true,
		isAiForbidden: true,
	},
	"xjzh_boss_lilisi": {
		sex: "female",
		group: "shen",
		hp: 6,
		skills: ["xjzh_boss_material", "xjzh_boss_lianji", "xjzh_boss_qiangji", "xjzh_boss_zenghen"],
		names: "null|null",
		rank: "legend",
		isUnseen: true,
		isAiForbidden: true,
	},
	"xjzh_boss_waershen": {
		sex: "male",
		group: "shen",
		hp: 12,
		skills: ["xjzh_boss_material", "xjzh_boss_fennu", "xjzh_boss_edu", "xjzh_boss_canren"],
		names: "null|null",
		rank: "legend",
		isUnseen: true,
		isAiForbidden: true,
	},
	"xjzh_boss_ttshilian": {
		sex: "double",
		group: "",
		hp: 0,
		skills: [],
		names: "null|null",
		rank: "legend",
		isUnseen: true,
		isAiForbidden: true,
	},

	//升华BOSS随从
	"xjzh_boss_duruierhy": {
		sex: "male",
		group: "shen",
		hp: 18,
		skills: ["xjzh_boss_mengdu"],
		names: "null|null",
		rank: "legend",
		isUnseen: true,
		isAiForbidden: true,
	},
	"xjzh_boss_yinaruisi": {
		sex: "double",
		group: "shen",
		hp: 12,
		skills: [],
		names: "null|null",
		rank: "legend",
		isBossAllowed: true,
		isHiddenBoss: true,
		isUnseen: true,
		isAiForbidden: true,
	},
	"xjzh_boss_masayier": {
		sex: "double",
		group: "shen",
		hp: 15,
		skills: [],
		names: "null|null",
		rank: "legend",
		isBossAllowed: true,
		isHiddenBoss: true,
		isUnseen: true,
		isAiForbidden: true,
	},
	"xjzh_boss_taernasha": {
		sex: "double",
		group: "shen",
		hp: 12,
		skills: [],
		names: "null|null",
		rank: "legend",
		isBossAllowed: true,
		isHiddenBoss: true,
		isUnseen: true,
		isAiForbidden: true,
	},
	"xjzh_boss_xiaotianshi": {
		sex: "double",
		group: "shen",
		hp: 4,
		skills: ["xjzh_boss_xiaoshenghui"],
		names: "null|null",
		rank: "legend",
		isBossAllowed: true,
		isHiddenBoss: true,
		isUnseen: true,
		isAiForbidden: true,
	},
	"xjzh_boss_datianshi": {
		sex: "double",
		group: "shen",
		hp: 4,
		skills: ["xjzh_boss_shilian", "xjzh_boss_dashenghui", "xjzh_boss_chiyan"],
		names: "null|null",
		rank: "legend",
		isBossAllowed: true,
		isHiddenBoss: true,
		isUnseen: true,
		isAiForbidden: true,
	},
	"xjzh_boss_gaotianshi": {
		sex: "double",
		group: "shen",
		hp: 4,
		skills: ["xjzh_boss_shilian", "xjzh_boss_gaoshenghui", "xjzh_boss_dacaijue"],
		names: "null|null",
		rank: "legend",
		isBossAllowed: true,
		isHiddenBoss: true,
		isUnseen: true,
		isAiForbidden: true,
	},
	"xjzh_boss_tianshizhang": {
		sex: "double",
		group: "shen",
		hp: 4,
		skills: ["xjzh_boss_shilian", "xjzh_boss_zhangshenghui", "xjzh_boss_dacaijue", "xjzh_boss_shenyou"],
		names: "null|null",
		rank: "legend",
		isBossAllowed: true,
		isHiddenBoss: true,
		isUnseen: true,
		isAiForbidden: true,
	},
	"xjzh_boss_duohunzhe": {
		sex: "double",
		group: "shen",
		hp: 4,
		skills: [],
		names: "null|null",
		rank: "legend",
		isBossAllowed: true,
		isHiddenBoss: true,
		isUnseen: true,
		isAiForbidden: true,
	},
	"xjzh_boss_duotianshi": {
		sex: "double",
		group: "shen",
		hp: 4,
		skills: [],
		names: "null|null",
		rank: "legend",
		isBossAllowed: true,
		isHiddenBoss: true,
		isUnseen: true,
		isAiForbidden: true,
	},
	"xjzh_boss_shachong": {
		sex: "double",
		group: "shen",
		hp: 4,
		skills: [],
		names: "null|null",
		rank: "legend",
		isBossAllowed: true,
		isHiddenBoss: true,
		isUnseen: true,
		isAiForbidden: true,
	},

};


for (let i in characters) {
	if (!characters[i].trashBin) characters[i].trashBin = [];
	let array = ["ext:仙家之魂/skin/yuanhua/" + i + ".jpg", "xjzh_die_audio"];
	if (game.getExtensionConfig("仙家之魂", "xjzh_lutoupifu") === true) array.splice(0, 1, "ext:仙家之魂/skin/lutou/" + i + ".jpg");
	characters[i].trashBin.addArray(array);

	if (!characters[i].dieAudios) characters[i].dieAudios = [];
	characters[i].dieAudios.add("ext:仙家之魂/audio/die/" + i + ".mp3");
};

export default characters;