const translates = {
	//众星之魂
	"xjzh_zxzh_linlingshiyu": "林凌&诗雨",
	"xjzh_zxzh_yuanyuan": "冯媛媛",
	"xjzh_zxzh_mufeng": "沐风",
	"xjzh_zxzh_moqinwu": "莫轻舞",
	"xjzh_zxzh_linziyan": "林子言",
	"xjzh_zxzh_moqinyan": "莫轻言",
	"xjzh_zxzh_yumuren": "余木人",
	"xjzh_zxzh_linmo": "林默",
	"xjzh_zxzh_jiangningzhi": "姜凝脂",

	"xjzh_zxzh_leifa": "雷法",
	"xjzh_zxzh_leifa_info": "锁定技，每个准备阶段开始时，你摸x张牌并弃x张牌，然后你可以与其拼点，若你赢，其受到一点雷电伤害且非锁定技失效直到回合结束(x为你的手牌数量+1)。",
	"xjzh_zxzh_jianxin": "剑心",
	"xjzh_zxzh_jianxin_info": "锁定技，你不因此技能造成/受到伤害时，若你装备了剑类武器，你观看牌堆顶x张牌，并合法使用其中所有[伤害]类卡牌，否则你可以将牌堆一张剑类武器置入武器栏(若伤害来源为你，x为你的体力值加本次伤害点数，否则为你已失去的体力加本次伤害点数)。",
	"xjzh_zxzh_jiezhen": "结阵",
	"xjzh_zxzh_jiezhen_info": "锁定技，你防止雷属性伤害；当你受到伤害时，若伤害来源在你的攻击范围内/外，你令攻击范围内/外（包括你）的一名随机角色代替你受到伤害。",
	"xjzh_zxzh_xianghun": "香魂",
	"xjzh_zxzh_xianghun_info": "出牌阶段限一次，你可以失去1点体力摸两张牌。",
	"xjzh_zxzh_renxin": "仁心",
	"xjzh_zxzh_renxin_info": "锁定技，当你失去体力后，你可以判定，若为红色，你可以令至多2名角色各回复一点体力，否则你可以对至多两名角色各造成一点雷属性伤害。",
	"xjzh_zxzh_xunqing": "寻情",
	"xjzh_zxzh_xunqing_info": "觉醒技，当你至少发动6次〖仁心〗后，你重置武将牌并回复体力至体力上限，然后你的技能〖仁心〗可以在其他角色对你造成伤害后和回合开始时发动。",
	"xjzh_zxzh_yufeng": "御风",
	"xjzh_zxzh_yufeng_info": "每回合限一次，当一名角色受到有来源的伤害时：<li>若该伤害是属性伤害，你可以弃置一张非基本牌并选择一名其他角色，令其受到等量属性伤害；<li>若该伤害是非属性伤害，你可以弃置一张基本牌令该伤害+1。",
	"xjzh_zxzh_fengzhen": "风阵",
	"xjzh_zxzh_fengzhen_info": "当一名角色使用一张【杀】,【南蛮入侵】或【万箭齐发】时，你可以弃置一张牌，选择任意名目标直到此牌结算结束，你选择的角色视为装备一张你声明的防具牌。",
	"xjzh_zxzh_zonghuo": "纵火",
	"xjzh_zxzh_zonghuo_info": "限定技,出牌阶段，你对自己造成1~2点火焰伤害，然后令所有其他角色选择：将装备区里的所有装备牌交给你(至少一张) ;或受到你的等量火焰伤害。",
	"xjzh_zxzh_shoutao": "守桃",
	"xjzh_zxzh_shoutao_info": "锁定技，你无法使用桃，你获得一张桃后，弃置之并将其移出游戏，此时若你已受伤，你回复一点体力，否则你摸两张牌，其他角色回复体力后，若你未受伤，你摸一张牌，否则你回复等量体力。",
	"xjzh_zxzh_taoyuan": "桃源",
	"xjzh_zxzh_taoyuan_info": "锁定技，你每弃置一张桃或不由弃桃回复体力时获得一个“桃”标记，当你濒死时，你弃置所有标记并回复等量体力，多余回复改为摸牌。",
	"xjzh_zxzh_qiwu": "起舞",
	"xjzh_zxzh_qiwu_info": "锁定技，出牌阶段限一次，你可以流失一点体力并摸两张牌，然后令场上除你之外的所有角色依次摸一张牌，若此牌为桃，你获得之。",
	"xjzh_zxzh_leifax": "雷法",
	"xjzh_zxzh_leifax_info": "其他角色出牌阶段开始前，你可以翻开牌堆顶一张牌，若不为♠，其需要弃置一张花色相同的牌，否则其于回合内非锁定技无效，然后你摸一张牌，若为♠，其受到一点雷电伤害，且本回合内你不能成为其使用卡牌的目标。",
	"xjzh_zxzh_leifax2": "雷法",
	"xjzh_zxzh_leifax2_info": "其他角色出牌阶段开始前，你可以翻开牌堆顶一张牌，若不为♠，其需要弃置两张花色相同的牌，否则其于回合内所有技能无效，然后你摸一张牌，若为♠，其受到两点雷电伤害，且本回合内你不能成为其使用卡牌的目标。",
	"xjzh_zxzh_leiyu": "雷域",
	"xjzh_zxzh_leiyu_info": "锁定技，摸牌阶段前或你的回合开始前，你可以选择一种花色直到你下次选择，你区域内所有牌均视为此花色，且当你成为此花色牌的目标后，你摸一张牌。",
	"xjzh_zxzh_tianxin": "天心",
	"xjzh_zxzh_tianxin_info": "出牌阶段，你可以展示牌堆顶x张牌，若其中♠牌的数量为最多之一，你选择一名不为你的角色令其受到y点雷电伤害，然后你将〖雷法〗描述中的一点雷电伤害改为两点，弃置一张牌改为两张牌，非锁定技失效改为所有技能失效，然后失去技能〖天心〗；否则你摸z张牌并受到一点雷电伤害（x为你的体力值，y为♠牌的数量，z为你已失去的体力）。",
	"xjzh_zxzh_cangjian": "藏剑",
	"xjzh_zxzh_cangjian_info": "锁定技，游戏开始时，你将牌堆中5-9张武器牌置于武将牌上称为“剑”并废除武器栏，此后每当你的回合开始时/结束时，你将一把“剑”洗入牌堆随机位置，然后你始终视为装备了此武器牌。",
	"xjzh_zxzh_jiantai": "剑胎",
	"xjzh_zxzh_jiantai_info": "锁定技，当你受到/造成伤害后，你可以展示牌堆顶x张牌，并获得其中所有的武器牌称为“剑胎”，若没有武器牌，则改为获得所有的装备牌；“剑胎”不计入手牌上限（x为已视为装备“剑”的数量+1）。",
	"xjzh_zxzh_yujian": "御剑",
	"xjzh_zxzh_yujian_info": "你可以将“剑胎”当作任意基本牌或非延时锦囊牌使用或打出",
	"xjzh_zxzh_yujian2": "御剑",
	"xjzh_zxzh_shiqiao": "拾樵",
	"xjzh_zxzh_shiqiao_info": "锁定技，场上所有进入弃牌堆的牌会被洗入牌堆随机位置。游戏开始时，你记录1-13中随机1-5个点数，当有牌被洗入牌堆时，若此牌点数已被你记录，你获得一张不同点数的牌，然后你移除该点数，当所有点数均被移除后，你重新记录之。",
	"xjzh_zxzh_baoxin": "抱薪",
	"xjzh_zxzh_baoxin_info": "锁定技，摸牌阶段、弃牌阶段，你随机展示牌堆13张牌，并获得其中所有与〖拾樵〗记录点数一致的牌，然后你跳过摸牌阶段、弃牌阶段；你使用〖拾樵〗包含点数的牌时，你移除〖拾樵〗中与之一致的点数并选择一项：1、摸2张牌;2、令此牌额外结算一次。",
	"xjzh_zxzh_baoxin_use": "抱薪",
	"xjzh_zxzh_moyu": "默语",
	"xjzh_zxzh_moyu_info": "你的准备阶段，你可以判定：♥你可以与一名角色交换体力值和体力上限；♠你可以令两名其他角色交换技能。",
	"xjzh_zxzh_zhenwen": "真纹",
	"xjzh_zxzh_zhenwen_info": "每回合限x次，当一名角色不因此技能获得技能时，若其为锁定技，你可以令其失去该技能并摸两张牌或令获得技能的角色改为你（x为当前游戏轮数）。",
	"xjzh_zxzh_jinyan": "禁言",
	"xjzh_zxzh_jinyan_info": "每回合限一次，其他角色发动技能后，你可以弃置1张牌禁用该技能直到你的下个回合开始。",
	"xjzh_zxzh_dianling": "点灵",
	"xjzh_zxzh_dianling_info": "其他角色回合开始时，若你有“屠苏”，你可以移除一个“屠苏”并令其当前回合阶段顺序逆转，然后该角色在回合内回复体力/失去体力/造成伤害时，你令一名其他角色执行相同的选项。",
	"xjzh_zxzh_tusu": "屠苏",
	"xjzh_zxzh_tusu_info": "锁定技，你始终跳过摸牌阶段/弃牌阶段，然后从牌堆获得X张牌名不一致的牌/X个“屠苏”标记，你使用这些牌无距离限制（X为你的体力上限）。",

	//流放之路
	"xjzh_poe_nvwu": "女巫",
	"xjzh_poe_yuansushi": "元素使",
	"xjzh_poe_yuhuoshi": "狱火师",
	"xjzh_poe_juedouzhe": "决斗者",
	"xjzh_poe_chuxing": "处刑者",
	"xjzh_poe_weishi": "卫士",
	"xjzh_poe_youxia": "游侠",
	"xjzh_poe_ruiyan": "锐眼",
	"xjzh_poe_guizu": "升华使徒",
	"xjzh_poe_diyuliequan": "地狱猎犬",
	"xjzh_poe_kuloufengbaofashi": "骷髅风暴法师",
	"xjzh_poe_kulouzonghuozhe": "骷髅纵火者",
	"xjzh_poe_kuloumushi": "骷髅牧师",

	"xjzh_poe_choice": "升华",
	"xjzh_poe_choice2": "升华",
	"xjzh_poe_zhaohuan": "召唤",
	"xjzh_poe_jianfeng": "剑风",
	"xjzh_poe_jianfeng_info": "出牌阶段限一次，你可以弃置一张[伤害]卡牌并指定一名其他角色，其可以选择弃置所有非[伤害]卡牌，或视为你对其使用一张不计次数且无视防具的【杀】，此【杀】额外结算1次，额外结算的【杀】造成伤害+1。",
	"xjzh_poe_tiaozhan": "挑战",
	"xjzh_poe_tiaozhan_info": "其他角色出牌阶段开始时，你可以摸3张牌并视为对其使用一张【决斗】(需合法），若你因此造成伤害，你令其弃置所有手牌，否则你弃置3张牌。",
	"xjzh_poe_sidou": "死斗",
	"xjzh_poe_sidou_info": "出牌阶段限一次，你可以将一张牌当决斗使用，若如此做，你与其区域内的所有牌均置入手牌区且视为【杀】直到手牌用尽或此牌结算，当此牌造成伤害后，若受到伤害的角色体力值小于其体力上限的一半(向上取整)，其立即失去所有体力。",
	"xjzh_poe_zhenya": "镇压",
	"xjzh_poe_zhenya_info": "<b><font color=orange>〖镇压〗</font>锁定技，你造成无属性伤害有10%几率暴击，场上每个存活的武将令此几率提高50%，每个阵亡的武将令此几率提高60%；若你的暴击几率不小于100%，你造成的暴击伤害为基础伤害的300%。",
	"xjzh_poe_zaixing": "灾星",
	"xjzh_poe_zaixing_info": "<b><font color=orange>〖传奇灾星〗</font>锁定技，你造成伤害后获得1点护甲（至多为3），你的每点护甲令你使用无属性【杀】可额外选择等量目标。",
	"xjzh_poe_lengxue": "冷血",
	"xjzh_poe_lengxue_info": "<b><font color=orange>〖刽子手〗</font>锁定技，当你造成无属性伤害令其陷入濒死状态，你令其立即死亡。",
	"xjzh_poe_shixue": "嗜血",
	"xjzh_poe_shixue_info": "<b><font color=orange>〖无尽饥饿〗</font>锁定技，你造成无属性伤害后，若你已受伤，你回复1点体力，否则你摸1张牌，若你本次伤害造成暴击，则你额外摸1张牌。",
	"xjzh_poe_canbao": "残暴",
	"xjzh_poe_canbao_info": "<b><font color=orange>〖影响〗</font>锁定技，你每击败一名武将令手牌上限、攻击距离、摸牌数、出牌次数+1",
	"xjzh_poe_yingxing": "影形",
	"xjzh_poe_yingxing_info": "<b><font color=orange>〖大师之形〗</font>锁定技，你的回合外，其他角色对你造成伤害后，你令其立即结束出牌阶段。",
	"xjzh_poe_jingji": "竞技",
	"xjzh_poe_jingji_info": "<b><font color=orange>〖竞技挑战者〗</font>锁定技，当你造成伤害后，你获得1枚“竞”标记（至多10个），每个标记为你提供6.5%反击几率和1%物理攻击格挡几率，“竞”标记将在你受到伤害后失去1枚。",
	"xjzh_poe_fuchou": "复仇",
	"xjzh_poe_fuchou_info": "<b><font color=orange>〖强力复仇〗</font>锁定技，你有50%基础物理攻击格挡几率，此后你每格挡一次物理攻击伤害，你获得+1%物理攻击格挡几率，至多60%。",
	"xjzh_poe_doushi": "斗士",
	"xjzh_poe_doushi_info": "<b><font color=orange>〖完美斗士〗</font>锁定技，你的法术攻击格挡几率等同于你的物理攻击格挡几率，你的格挡上限+10%；你的防具栏无法被废除",
	"xjzh_poe_zhuzao": "铸造",
	"xjzh_poe_zhuzao_info": "<b><font color=orange>〖痛苦铸造〗</font>锁定技，你的反击造成双倍伤害；你的格挡几率+10%，你的反击几率+10%。",
	"xjzh_poe_xueyan": "血眼",
	"xjzh_poe_xueyan_info": "<b><font color=orange>〖血之眼〗</font>锁定技，你的体力回复量+1，若你回复体力后未受伤，你获得+2%物理攻击格挡几率。",
	"xjzh_poe_baipiao": "白嫖",
	"xjzh_poe_baipiao_info": "<b><font color=orange>〖免费力量〗</font>锁定技，当你受到伤害后，若你未装备防具牌，你随机装备一张防具牌，否则你将一张牌堆随机一张防具牌置于弃牌堆，然后视为你装备了该防具牌。",
	"xjzh_poe_jingzhun": "精准",
	"xjzh_poe_jingzhun_info": "出牌阶段，你可以展示牌堆顶一张牌，若不为[伤害]卡牌，你获得此牌，否则你可以视为使用一张【杀】（此杀不计入出牌次数），并且此技能失效直到回合结束。",
	"xjzh_poe_diaoling": "凋零",
	"xjzh_poe_diaoling_info": "锁定技，你的回合开始时/受到伤害时，你令附近角色/伤害来源获得1层中毒；你对目标附加的中毒无上限。",
	"xjzh_poe_fenlie": "分裂",
	"xjzh_poe_fenlie_info": "<b><font color=orange>〖无限弹药〗</font>锁定技，你使用指定单个目标且不为你的[伤害]卡牌可以额外选择一个目标，若你装备了武器牌，你可以额外选择两个目标（额外选择目标不受距离限制）",
	"xjzh_poe_tanshe": "弹射",
	"xjzh_poe_tanshe_info": "<b><font color=orange>〖致命连锁〗</font>锁定技，你造成伤害有30%几率对其附近随机一个武将造成一点伤害。",
	"xjzh_poe_juji": "狙击",
	"xjzh_poe_juji_info": "<b><font color=orange>〖狙击〗</font>锁定技，当你造成伤害时，若你不在其周围，你对其额外造成60%伤害（向下取整）。",
	"xjzh_poe_jufeng": "飓风",
	"xjzh_poe_jufeng_info": "<b><font color=orange>〖飓风之力〗</font>锁定技，你发动〖分裂〗〖弹射〗及你于回合内使用牌时获得一个“风”标记，你最多拥有10个风标记，你拥有标记时获得飓风效果，你和你的友军均具备[飓风]效果（强制翻开身份牌）。",
	"xjzh_poe_danmu": "弹幕",
	"xjzh_poe_danmu_info": "<b><font color=orange>〖弹幕〗</font>锁定技，你的弹射不再令附近武将受伤，改为令你已造成伤害的武将额外受到一点伤害，你使用卡牌指定不为你的目标时，有30%几率令其获得一个“残”标记，每个标记令其有25%几率造成伤害无效。",
	"xjzh_poe_shenghua": "升华",
	"xjzh_poe_shenghua_info": "锁定技，你不需要禁用技能；游戏开始时/你的准备阶段，你展示POE武将的10个技能并选择其中5个获得之直到你下次选择获得技能。",
	"xjzh_poe_shenghuajin": "升华·禁",
	"xjzh_poe_huoqiu": "火球",
	"xjzh_poe_huoqiu_info": "锁定技，你的所有红色手牌视为【火杀】，你使用【火杀】无距离与次数限制，你使用【火杀】造成伤害令该伤害向下传导x次（x为你本回合使用【火杀】造成伤害的次数）",
	"xjzh_poe_mishu": "秘术",
	"xjzh_poe_mishu_info": "锁定技，当你使用牌指定目标或成为其他角色的卡牌目标时，若你的手牌小于其，你将手牌补至与其一致，然后你可以指定一名其他角色，令其也成为此牌目标。",
	"xjzh_poe_liequan": "猎犬",
	"xjzh_poe_liequan_info": "锁定技，你的回合开始时/造成火属性伤害后，你召唤一只地狱猎犬至场上。",
	"xjzh_poe_ranhuo": "燃火",
	"xjzh_poe_ranhuo_info": "锁定技，你的回合开始时，你令周围所有敌方角色获得一层燃烧；你令你的召唤师对被点燃的角色造成伤害+1。",
	"xjzh_poe_huiliu": "汇流",
	"xjzh_poe_huiliu_info": "<b><font color=orange>〖元素汇流〗</font>锁定技，每个回合开始时，你随机获得一种元素汇流，并移除其他元素汇流，你拥有元素汇流时，你造成的所有伤害视为该元素属性伤害并防止你受到其他元素属性伤害。",
	"xjzh_poe_guangta": "光塔",
	"xjzh_poe_guangta_info": "<b><font color=orange>〖毁灭光塔〗</font>你造成属性伤害后可以令其附近一名角色受到等量伤害，若此伤害类型为火焰/冰霜/闪电，则你令其获得一层感电/燃烧/冰冻。",
	"xjzh_poe_sangzhong": "丧钟",
	"xjzh_poe_sangzhong_info": "<b><font color=orange>〖死亡丧钟〗</font>锁定技，每当你第2次失去牌后，你摸1张牌，你使用这两张牌无距离限制。",
	"xjzh_poe_suxing": "塑形",
	"xjzh_poe_suxing_info": "<b><font color=orange>〖元素塑形〗</font>锁定技，你造成属性伤害无法被防止；你使用有属性的牌可以额外指定一个目标且无次数限制。",
	"xjzh_poe_bilei": "壁垒",
	"xjzh_poe_bilei_info": "<b><font color=orange>〖元素壁垒〗</font>锁定技，你获得此技能时，你获得20点护甲，当你的所有护甲被移除后，你受到3倍于你体力上限的无来源伤害，若你未因此阵亡，你获得20点护甲，然后你可以将你本局游戏中受到的所有伤害视为随机一种属性伤害任意分配给其他角色。",
	"xjzh_poe_qinhe": "亲和",
	"xjzh_poe_qinhe_info": "<b><font color=orange>〖元素亲和〗</font>出牌阶段限一次，你可以选择一名角色并展示其手牌，并获得其手牌中所有♥牌和♠牌，然后其中每有一张♥牌视为其使用一张【桃】，每有一张♠令其视为使用一张【酒】。",
	"xjzh_poe_yuquan": "狱犬",
	"xjzh_poe_yuquan_info": "<b><font color=orange>〖忠诚狱犬〗</font>锁定技，当不应此技能你召唤时，你额外召唤一只地狱猎犬至场上（场上只能有一只由你召唤的地狱猎犬），且你受到伤害有20%几率由地狱猎犬承受。",
	"xjzh_poe_huoji": "火祭",
	"xjzh_poe_huoji_info": "<b><font color=orange>〖火祭协议〗</font>锁定技，你使用牌无次数和距离限制；你每使用一张牌获得一点炼狱之炎，当炼狱之炎不小于你的体力上限时，你受到等量火焰伤害；你的炼狱之炎每回合移去一点。",
	"xjzh_poe_feiteng": "沸腾",
	"xjzh_poe_feiteng_info": "<b><font color=orange>〖沸腾之躯〗</font>锁定技，若你有炼狱之炎，你与友军造成火焰伤害+1，然后你获得等量护甲。",
	"xjzh_poe_xianji": "献祭",
	"xjzh_poe_xianji_info": "<b><font color=orange>〖生命献祭〗</font>锁定技，你锁定体力上限为你初始体力上限的一半，获得并锁定2倍于你献祭的体力上限点护甲。",
	"xjzh_poe_shenyou": "神佑",
	"xjzh_poe_shenyou_info": "<b><font color=orange>〖神佑之躯〗</font>锁定技，你有50%几率防止火焰伤害；你受到的其他伤害视为火焰伤害。",
	"xjzh_poe_shikui": "尸傀",
	"xjzh_poe_shikui_info": "<b><font color=orange>〖尸体复苏〗</font>锁定技，游戏开始时，你选择召唤骷髅纵火者、骷髅牧师、骷髅风暴法师之二于场上，场上每有一个召唤物，你摸牌时额外摸一张牌；其他角色阵亡后，你在随机位置将其复苏为以上三种召唤物之一。。",
	"xjzh_poe_fusu": "复苏",
	"xjzh_poe_fusu_info": "锁定技，每轮开始时，你令所有友方召唤物和召唤师回复随机1-x点体力并摸随机1-x张牌（x为场上与你召唤师一致的召唤物的数量，至低为1）。",
	"xjzh_poe_zonghuo": "纵火",
	"xjzh_poe_zonghuo_info": "锁定技，你令场上所有敌方角色的燃烧层数突破上限；当你的召唤师造成火属性伤害时，你有几率令随机一名敌方角色受到一点火属性伤害。",
	"xjzh_poe_fengbao": "风暴",
	"xjzh_poe_fengbao_info": "锁定技，你对敌方造成伤害会令其感电，且你造成的感电层数不受上限影响。",

	//王者荣耀
	"xjzh_wzry_libai": "李白",
	"xjzh_wzry_yuange": "元歌",
	"xjzh_wzry_yao": "东方曜",
	"xjzh_wzry_ganjiangmoye": "干将莫邪",
	"xjzh_wzry_haiyue": "海月",
	"xjzh_wzry_huamulan": "花木兰",
	"xjzh_wzry_duoliya": "朵莉亚",

	"xjzh_wzry_xiaxing": "侠行",
	"xjzh_wzry_xiaxing_info": "锁定技，你造成伤害获得一道剑气，每道剑气令你使用牌可以额外指定一名其他角色为目标，你获得四道剑气时摸等量牌并解锁〖剑歌〗直到回合结束，然后你并失去所有剑气。",
	"xjzh_wzry_jinjiu": "进酒",
	"xjzh_wzry_jinjiu_info": "出牌阶段限一次，你可以与一名攻击范围内的其他角色交换位置，然后你视为使用一张【酒】并摸x张牌，回合结束后，你返回原位置；你使用【杀】次数+x（x为其与你的座位号差值的绝对值）。",
	"xjzh_wzry_jiange": "剑歌",
	"xjzh_wzry_jiange_info": "锁定技，当你解锁该技能后，你使用牌可以额外选择任意名角色；出牌阶段限5次，你可以弃置一种类型的手牌，然后摸等量牌，若本次摸牌的牌中有类型、花色、点数任意一项全部一致，你摸等量牌并重复执行该流程。",
	"xjzh_wzry_xingchen": "星辰",
	"xjzh_wzry_xingchen_info": "锁定技，你受到伤害转为星削15s后结算；你累计发动三次不为〖星辰〗的技能后摸牌至4张并视为使用一张【万箭齐发】。",
	"xjzh_wzry_liekong": "裂空",
	"xjzh_wzry_liekong_info": "出牌阶段限一次，你可以弃置4张花色不同的牌并选择一名其他角色，然后其须弃置等量花色一致的牌，其每少弃置一张牌，视为你对其使用一张不计入次数的【杀】。",
	"xjzh_wzry_guichen": "归尘",
	"xjzh_wzry_guichen_info": "锁定技，你的出牌阶段开始时，你记录你的当前状态；本局游戏濒死时限一次，出牌阶段，若你有记录的状态，你可以回到你记录的状态。",
	"xjzh_wzry_jianzhong": "剑冢",
	"xjzh_wzry_jianzhong_info": "锁定技，每当你造成1点伤害后，你将牌堆顶1张牌置于武将牌上称为“剑”，最多10把“剑”；若你有“剑”，你造成伤害+x（x为“剑”的种类数量）。",
	"xjzh_wzry_cuijian": "淬剑",
	"xjzh_wzry_cuijian_info": "锁定技，若你装备了/未装备武器牌，你使用基本牌/非延时锦囊牌额外结算一次。",
	"xjzh_wzry_jianlai": "剑来",
	"xjzh_wzry_jianlai_info": "锁定技，当你的“剑”不少于10时，你获得所有“剑”，你使用“剑”无次数和距离限制，然后〖剑来〗、〖剑冢〗的基础数量+10。",
	"xjzh_wzry_bieyue": "别月",
	"xjzh_wzry_bieyue_info": "锁定技，游戏开始时，你获得4个“月”标记，此后每隔50s你获得1个“月”，你最多只能拥有4个“月”；你可以移除一个“月”令你摸牌阶段额外摸一张牌或跳过判定、弃牌阶段、解除翻面",
	"xjzh_wzry_shunhua": "瞬华",
	"xjzh_wzry_shunhua_info": "出牌阶段，你可以选择至多x名角色，令其获得一个“月”标记，然后你移除等量标记(x为你拥有的标记数量)。",
	"xjzh_wzry_liuguang": "流光",
	"xjzh_wzry_liuguang_info": "锁定技，你对有“月”的角色使用【杀】无视距离和防具；当你使用【杀】指定目标时，你令除你之外所有有“月”的角色选择：交给你一张牌或成为此【杀】目标，若其已有“月”，则此牌额外对其结算一次，然后其移除“月”标记。",
	"xjzh_wzry_liuguang2": "流光",
	"xjzh_wzry_liuguang2_info": "锁定技，其他角色计算与你距离+1，你使用牌无距离限制且你使用牌次数*2，你使用【杀】无视防具且令其选择：交给你一张牌或此【杀】额外结算一次。",
	"xjzh_wzry_huanhai": "幻海",
	"xjzh_wzry_huanhai_info": "限定技，出牌阶段，若你有“月”且当前轮数不为1且你的体力值不小于2，你选择一名角色并移除场上其他角色的所有“月”，然后你将“月”补至4个，禁用〖瞬华〗并修改〖流光〗直到〖幻海〗结束，然后令除你与其之外的其他角色暂时离开游戏直到你与其任意一名角色阵亡或你失去所有“月”，然后你获得等同于你体力值的护甲，且此后你每造成一点伤害获得一点护甲，〖幻海〗持续持续时间结束后，你获得等同于你护甲数量个“月”并移除所有护甲(不受〖别月〗标记上限限制)。",
	"xjzh_wzry_huanhai_append": "注：若当前游戏为第一轮且你的体力大于1，你无法发动〖幻海〗",
	"xjzh_wzry_xunshou": "巡守",
	"xjzh_wzry_xunshou_info": "锁定技，你对其他角色造成伤害后，其须将一张牌置于武将牌上称为“巡”，然后你摸两张牌，当其武将牌上有4张“巡”时，你对其造成一点伤害并禁用其所有技能直到其再次受到伤害后，然后其弃置所有“巡”。",
	"xjzh_wzry_konglie": "空烈",
	"xjzh_wzry_konglie_info": "出牌阶段，你可以选择并使用场上的一张“巡”，你使用此牌无需合法性判定。",
	"xjzh_wzry_daofeng": "刀锋",
	"xjzh_wzry_daofeng_info": "转换技，你的回合开始时，你获得附近所有角色各一张牌。<li>阴：每个出牌阶段开始时，若场上有“巡”，你可以展示并从场上“巡”中弃置至多4张花色不一致的牌，然后对一名其他角色造成等量伤害。<li>阳：当你受到伤害或体力流失时，若场上“巡”的数量不大于4，你防止之，然后你可以令一名角色将一张牌置于武将牌上称为“巡”，否则你摸两张牌",
	"xjzh_wzry_huange": "欢歌",
	"xjzh_wzry_huange_info": "回合开始时，你可以选择/重新选择一名其他角色成为你的契约队友，其手牌数量及手牌上限始终不小于你的手牌数量和手牌上限；若你已选择契约队友，你的手牌上限+2。",
	"xjzh_wzry_zhulang": "逐浪",
	"xjzh_wzry_zhulang_info": "锁定技，你摸牌后，若你已选择契约队友，你额外摸等量牌，然后你将这些牌的任意张牌交给你的契约队友（至少一张），若如此做，你与其各回复一点体力。",
	"xjzh_wzry_tiannai": "天籁",
	"xjzh_wzry_tiannai_info": "限定技，出牌阶段，你可以失去一点体力上限，然后令你的契约队友清除控制效果并重置其所有技能，然后其获得增益技能〖破晓〗。",
	"xjzh_wzry_kongou": "控偶",
	"xjzh_wzry_kongou_info": "锁定技，持恒技，当你造成伤害后或对一名其他角色使用牌后，你获得其2/1个武将碎片；你的武将碎片背包每有10个可用的武将，此数值+1。",
	"xjzh_wzry_miying": "秘影",
	"xjzh_wzry_miying_info": "出牌阶段，你可以消耗50武将碎片将武将牌替换为你选择的武将并摸牌至体力上限直到该武将阵亡或你主动切换为“元歌”；当你从傀儡切换为本体时，你回复一点体力并摸两张牌；你切换傀儡或本体时均会清除所有控制效果；当你切换为傀儡时，保留技能〖纸鸢〗。",
	"xjzh_wzry_zhiyuan": "纸鸢",
	"xjzh_wzry_zhiyuan_info": "出牌阶段限一次，若场上存在你武将碎片背包中的武将且你可切换为傀儡，你可以选择一名该武将，复制其装备区和手牌区，以此法获得的手牌不计入上限；若你未切换/已切换为傀儡，你与其他角色计算距离-1/使用【杀】的次数+1。",

	//暗黑破坏神
	"xjzh_diablo_lamasi": "拉斯玛",
	"xjzh_diablo_moruina": "莫瑞娜",
	"xjzh_diablo_kaxia": "卡夏",
	"xjzh_diablo_yafeikela": "亚菲克拉",
	"xjzh_diablo_xiong": "变形·熊",
	"xjzh_diablo_lang": "变形·狼",
	"xjzh_diablo_lilisi": "莉莉丝",
	"xjzh_diablo_nataya": "娜塔亚",
	"xjzh_diablo_kelike": "科里克",

	"xjzh_diablo_hunhuo": "魂火",
	"xjzh_diablo_hunhuo_info": "锁定技，当你击败一名角色后，你将其灵魂收入死亡之书中；出牌阶段限一次，你可以消耗一个灵柩将死亡之书中收集的灵魂唤醒至场上为你作战，唤醒的角色拥有〖尸爆〗；当你濒死时，你可以与死亡之书中的一个灵魂交换身体。",
	"xjzh_diablo_hunhuo_use": "魂火",
	"xjzh_diablo_shibao": "尸爆",
	"xjzh_diablo_shibao_info": "锁定技，当你阵亡后，附近角色受到一点无来源伤害；每个回合结束后，若你的身份与拉马斯不一致/不为同一阵营，你立即阵亡",
	"xjzh_diablo_hunhuo_append": "注：死亡之书中的灵魂除非拉马斯主动解放，否则无法再以选将的形式出现在场上；游戏开始时，拉马斯会从死亡之书每个灵魂上随机获得一个技能（限定技、主公技、觉醒技除外），并根据灵魂数量(灵魂数量/3，向下取整)获得不同技能",
	"xjzh_diablo_haoling": "号令",
	"xjzh_diablo_haoling_info": "出牌阶段限一次，你可以选择一名被你唤醒的角色，然后令其摸一张牌并使用一张你指定目标的[伤害]卡牌，当前回合结束后，你执行一个额外的回合。",
	"xjzh_diablo_luanshe": "乱射",
	"xjzh_diablo_luanshe_info": "锁定技，当你使用【杀】指定目标时，此【杀】增加1个不为你和初始目标的随机额外目标（需合法）。",
	"xjzh_diablo_jingshe": "劲射",
	"xjzh_diablo_jingshe_info": "锁定技，当你使用【杀】指定了多个目标时，你令其中一个目标获得1层易伤。",
	"xjzh_diablo_guanzhu": "灌注",
	"xjzh_diablo_guanzhu_info": "你摸牌后，你可以选择令其中至多两张[伤害]卡牌获得灌注效果，你使用有灌注效果的牌无次数限制，且若你因此牌造成伤害，其获得对应一层灌注属性类型buff，灌注效果会被重新选择的灌注效果覆盖。",
	"xjzh_diablo_guanzhu_fire": "火焰灌注",
	"xjzh_diablo_guanzhu_ice": "冰霜灌注",
	"xjzh_diablo_guanzhu_poison": "毒素灌注",
	"xjzh_diablo_sushe": "速射",
	"xjzh_diablo_sushe_info": "锁定技，你使用【杀】额外结算1-2次。",
	"xjzh_diablo_yingbi": "隐蔽",
	"xjzh_diablo_yingbi_info": "出牌阶段限一次，你可以移除所有控制效果并令你攻击范围内的所以角色获得易伤，然后摸等量牌。",
	"xjzh_diablo_jianyu": "箭雨",
	"xjzh_diablo_jianyu_info": "出牌阶段，你可以视为使用一张【万箭齐发】,冷却时间120秒。",
	"xjzh_diablo_shilue": "施虐",
	"xjzh_diablo_shilue_info": "锁定技，你每使用1张牌，随机回复1-5点魔力；你拥有魔力抵抗。",
	"xjzh_diablo_shihua": "石化",
	"xjzh_diablo_shihua_info": "锁定技，你回复魔力时摸1张牌。",
	"xjzh_diablo_jufeng": "飓风",
	"xjzh_diablo_jufeng_info": "当你造成伤害后，你可以消耗45点魔力令其获得1层易伤；拥有易伤的角色造成伤害后，你摸1张牌。",
	"xjzh_diablo_leibao": "雷暴",
	"xjzh_diablo_leibao_info": "出牌阶段，你可以消耗45点魔力，令场上所有易伤的角色受到1点雷属性伤害，若场上没有易伤角色，你令1名角色获得1层易伤；<li>会心：你有30%几率发动该技能不消耗魔力。",
	"xjzh_diablo_zhongou": "重欧",
	"xjzh_diablo_zhongou_info": "熊人技能，锁定技，你使用[伤害]卡牌只能指定一个目标，你使用的[伤害]卡牌无视防具，若此牌造成伤害，你可以消耗35点灵力获得x点护甲并强固x点体力值（x为技能等级）。<br><br><li>会心：你有25%几率因此技能造成伤害时令目标获得一层减速。",
	"xjzh_diablo_fensui": "粉碎",
	"xjzh_diablo_fensui_info": "大地技能，锁定技，若你使用牌指定目标时未受伤，此牌结算两次；每隔6个回合，你下一次造成伤害翻倍。<br><br><li>会心：你有50%几率令因此技能受到伤害的目标眩晕。",
	"xjzh_diablo_duguan": "毒灌",
	"xjzh_diablo_duguan_info": "当你造成伤害时，你可以消耗25点魔力令其视为毒属性伤害，你对中毒的目标造成伤害时，会心几率提高50%。<br><br><li>会心：你有33%几率发动该技能时不消耗魔力；你有25%几率造成毒属性伤害时令其获得一层中毒。",
	"xjzh_diablo_xianjing": "陷阱",
	"xjzh_diablo_xianjing_info": "出牌阶段限一次，你可以观看牌堆随机x（x为牌堆牌的数量的百分之一并向上取整）张牌，并将其标记为“剧毒陷阱”，然后将这些牌洗入牌堆随机位置，当其他角色获得此牌时，其获得最大层数中毒。<br><br><li>会心：其他角色获得此牌时，你有20%几率摸2张牌并获得此牌；你有30%几率回复25点魔力。",
	"xjzh_diablo_baolu": "暴露",
	"xjzh_diablo_baolu_info": "锁定技，每当你对“中毒”的角色造成1点伤害时，令此伤害视为毒属性伤害且+1。<br><br><li>会心：你有25%几率发动技能〖陷阱〗。",

	//地下城与勇士
	"xjzh_dnf_suodeluosi": "索德罗斯",
	"xjzh_dnf_luoshibahe": "罗什巴赫",

	"xjzh_dnf_tiannai": "天籁",
	"xjzh_dnf_tiannai_info": "当一名角色不因此技能回复体力后或受到伤害后，你可以消耗30点魔力令其回复1点体力，然后若其未受伤，其获得1点体力上限。",
	"xjzh_dnf_zhufu": "祝福",
	"xjzh_dnf_zhufu_info": "出牌阶段，你可以消耗35点魔力并选择一名被控制的角色，令其清除所有控制效果，然后其下一次造成伤害+1并防止下一次受到伤害（两种效果仅生效其中一种）。",
	"xjzh_dnf_shengyu": "圣愈",
	"xjzh_dnf_shengyu_info": "锁定技，每个回合结束时，你回复5点魔力，然后若场上有被祝福的角色，你与其各摸1张牌，然后若你的魔力为最大值，你获得5点魔力上限，并令一名其他角色执行一个额外的回合，该回合内，其每使用一张牌，你回复1点魔力，额外的回复改为其摸1张牌。",
	"xjzh_jujian": "巨剑",
	"xjzh_guangjian": "光剑",
	"xjzh_dunqi": "钝器",
	"xjzh_duanjian": "短剑",
	"xjzh_taidao": "太刀",
	"xjzh_dnf_jianshen": "剑神",
	"xjzh_dnf_jianshen_info": "锁定技，场上其他角色无法使用牌名、描述中有“剑”的牌；你的准备阶段、结束阶段，你选择并装备【魔剑·克拉丽丝】、【巨力黄金锤】、【天脊骨狱息】、【天丛云剑】、【名刀·观世正宗】",
	"xjzh_dnf_aoyi": "奥义",
	"xjzh_dnf_aoyi_info": "锁定技，你的武器栏无法废除，你切换武器牌时获得附近角色各一张手牌，并根据你此时装备的武器牌类型获得不同效果：<li>光剑，移除你的所有控制效果；<li>巨剑，令附近随机一名敌方角色武将牌翻至背面；<li>短剑，对附近随机一名敌方角色造成一点伤害；<li>太刀，弃置周围所有敌方角色的武器牌；<li>钝器，令周围随机一名敌方角色陷入混乱。",
	"xjzh_card_mojianklls": "魔剑·克拉丽丝",
	"xjzh_card_mojianklls_info": "巨剑：你造成伤害无法被防止。",
	"xjzh_card_mojianklls_skill": "魔剑·克拉丽丝",
	"xjzh_card_mojianklls_skill_info": "你造成伤害无法被防止。",
	"xjzh_card_julihjc": "巨力黄金锤",
	"xjzh_card_julihjc_info": "钝器：你使用【杀】造成伤害可以令其跳过下个出牌阶段。",
	"xjzh_card_julihjc_skill": "巨力黄金锤",
	"xjzh_card_julihjc_skill_info": "你使用【杀】造成伤害可以令其跳过下个出牌阶段。",
	"xjzh_card_tianjigyx": "天脊骨狱息",
	"xjzh_card_tianjigyx_info": "光剑：你使用【杀】次数为2，你造成伤害令其感电，若其已感电，你使用【杀】次数+1。",
	"xjzh_card_tianjigyx_skill": "天脊骨狱息",
	"xjzh_card_tianjigyx_skill_info": "你使用【杀】次数为2，你造成伤害令其感电，若其已感电，你使用【杀】次数+1。",
	"xjzh_card_guanshizhengzong": "观世正宗",
	"xjzh_card_guanshizhengzong_info": "太刀：你使用【杀】造成伤害令其获得一层易伤，若其已有易伤且易伤层数达到上限，你令其移除所有易伤并对其造成等量伤害。",
	"xjzh_card_guanshizhengzong_skill": "观世正宗",
	"xjzh_card_guanshizhengzong_skill_info": "你使用【杀】造成伤害令其获得一层易伤，若其已有易伤且易伤层数达到上限，你令其移除所有易伤并对其造成等量伤害。",
	"xjzh_card_tiancongyunjian": "天丛云剑",
	"xjzh_card_tiancongyunjian_info": "短剑：你使用【杀】造成伤害后，可以选择一名其他角色令其受到一点无来源伤害。",
	"xjzh_card_tiancongyunjian_skill": "天丛云剑",
	"xjzh_card_tiancongyunjian_skill_info": "你使用【杀】造成伤害后，可以选择一名其他角色令其受到一点无来源伤害。",
	"xjzh_dnf_jianyi": "剑意",
	"xjzh_dnf_jianyi_info": "当你受到伤害时，若你未装备武器牌，你可以发动〖剑神〗切换武器牌，否则根据你装备的武器类型获得不同效果：<li>光剑，对伤害来源造成等量伤害并令其获得一层感电<li>巨剑，防止无属性伤害并令伤害来源视为对你选择的一名其他角色使用一张不计入次数的【杀】<li>短剑，你摸两张牌<li>太刀，令其选择弃置伤害点数张牌或令你回复一点体力<li>钝器，令其立即结束当前出牌阶段。",

	//西游释厄传
	"xjzh_xyj_sunwukong": "孙悟空",

	"xjzh_xyj_tianhuo": "天火",
	"xjzh_xyj_tianhuo_info": "本局游戏限三次，出牌阶段，你可以将任意张♦牌交给你的下家/上家，其需选择并交给其下家/上家x+1张牌直到其为你时，否则你对其造成x点火焰伤害然后终止技能流程。（x为其上家/下家选择的牌的数量）。",
	"xjzh_xyj_dongcha": "洞察",
	"xjzh_xyj_dongcha_info": "锁定技，场上其他角色手牌对你可见，你摸牌阶段摸牌数+2。",
	"xjzh_xyj_ruyi": "如意",
	"xjzh_xyj_ruyi_info": "锁定技，每当你不因〖天火〗造成/受到火焰伤害后，你随机获得【天罡火】、【混元丹】、【照妖镜】、【火云刀】、【定身咒】之一，以上五张牌不计入手牌上限且无法被弃置/获得。",
	"xjzh_card_tianganghuo": "天罡火",
	"xjzh_card_tianganghuo_info": "出牌阶段对自己使用，获得一次〖天火〗使用次数。",
	"xjzh_card_hunyuandan": "混元丹",
	"xjzh_card_hunyuandan_info": "出牌阶段对自己使用，将手牌补至体力上限（手牌中的【天罡火】、【混元丹】、【照妖镜】、【火云刀】、【定身咒】不记入手牌数量），然后你于本回合内使用牌无次数限制。",
	"xjzh_card_zhaoyaojing": "照妖镜",
	"xjzh_card_zhaoyaojing_info": "出牌阶段对其他角色使用，其需弃置所有♦手牌，否则其失去一点体力上限。",
	"xjzh_card_huoyundao": "火云刀",
	"xjzh_card_huoyundao_info": "你使用无属性【杀】时可将其改为【火杀】。",
	"xjzh_card_dingshenzhou": "定身咒",
	"xjzh_card_dingshenzhou_info": "出牌阶段对其他角色使用，令其跳过下个出牌阶段和弃牌阶段。",

};

export default translates;