window.xjzh_updateversion={
	version:'3.06201',
	update:'3.06181',
	files:[
			"LICENSE",
			"info.json",
			"extension.js",

			"ext/1_Skin.js",
			"ext/2_PoeMode.js",
			"ext/3_Buff.js",
			"ext/achievement.js",
			"ext/animation.js",
			"ext/gonglve.js",
			"ext/qishuyaojians.js",
			"ext/qsyjOption.js",

			"ext/html5/css3-mediaqueries.js",
			"ext/html5/html5shiv.js",

			"css/mainPage.css",

			"ext/modules/CHRskills/index.js",

			"ext/modules/Title/index.js",

			"ext/modules/update/index.js",

			"ext/modules/update/source.js",

			"ext/modules/update/update.js",

			"ext/modules/config/index.js",

			"ext/modules/package/index.js",

			"ext/modules/index.js",

			"ext/modules/cards/index.js",
			"ext/modules/cards/card.js",
			"ext/modules/cards/skill.js",
			"ext/modules/cards/translate.js",
			"ext/modules/cards/list.js",

			"ext/modules/mathList/index.js",

			"ext/modules/character/XWSG/card.js",
			"ext/modules/character/XWSG/character.js",
			"ext/modules/character/XWSG/characterFilter.js",
			"ext/modules/character/XWSG/characterReplace.js",
			"ext/modules/character/XWSG/characterTitle.js",
			"ext/modules/character/XWSG/dynamicTranslate.js",
			"ext/modules/character/XWSG/index.js",
			"ext/modules/character/XWSG/intro.js",
			"ext/modules/character/XWSG/pinyin.js",
			"ext/modules/character/XWSG/skill.js",
			"ext/modules/character/XWSG/sort.js",
			"ext/modules/character/XWSG/translate.js",
			"ext/modules/character/XWSG/voices.js",

			"ext/modules/character/XWTR/card.js",
			"ext/modules/character/XWTR/character.js",
			"ext/modules/character/XWTR/characterFilter.js",
			"ext/modules/character/XWTR/characterReplace.js",
			"ext/modules/character/XWTR/characterTitle.js",
			"ext/modules/character/XWTR/dynamicTranslate.js",
			"ext/modules/character/XWTR/index.js",
			"ext/modules/character/XWTR/intro.js",
			"ext/modules/character/XWTR/pinyin.js",
			"ext/modules/character/XWTR/skill.js",
			"ext/modules/character/XWTR/sort.js",
			"ext/modules/character/XWTR/translate.js",
			"ext/modules/character/XWTR/voices.js",

			"ext/modules/character/XWDM/card.js",
			"ext/modules/character/XWDM/character.js",
			"ext/modules/character/XWDM/characterFilter.js",
			"ext/modules/character/XWDM/characterReplace.js",
			"ext/modules/character/XWDM/characterTitle.js",
			"ext/modules/character/XWDM/dynamicTranslate.js",
			"ext/modules/character/XWDM/index.js",
			"ext/modules/character/XWDM/intro.js",
			"ext/modules/character/XWDM/pinyin.js",
			"ext/modules/character/XWDM/skill.js",
			"ext/modules/character/XWDM/sort.js",
			"ext/modules/character/XWDM/translate.js",
			"ext/modules/character/XWDM/voices.js",

			"ext/modules/character/XWCS/card.js",
			"ext/modules/character/XWCS/character.js",
			"ext/modules/character/XWCS/characterFilter.js",
			"ext/modules/character/XWCS/characterReplace.js",
			"ext/modules/character/XWCS/characterTitle.js",
			"ext/modules/character/XWCS/dynamicTranslate.js",
			"ext/modules/character/XWCS/index.js",
			"ext/modules/character/XWCS/intro.js",
			"ext/modules/character/XWCS/pinyin.js",
			"ext/modules/character/XWCS/skill.js",
			"ext/modules/character/XWCS/sort.js",
			"ext/modules/character/XWCS/translate.js",
			"ext/modules/character/XWCS/voices.js",

			"ext/modules/character/XWTZ/card.js",
			"ext/modules/character/XWTZ/character.js",
			"ext/modules/character/XWTZ/characterFilter.js",
			"ext/modules/character/XWTZ/characterReplace.js",
			"ext/modules/character/XWTZ/characterTitle.js",
			"ext/modules/character/XWTZ/dynamicTranslate.js",
			"ext/modules/character/XWTZ/index.js",
			"ext/modules/character/XWTZ/intro.js",
			"ext/modules/character/XWTZ/pinyin.js",
			"ext/modules/character/XWTZ/skill.js",
			"ext/modules/character/XWTZ/sort.js",
			"ext/modules/character/XWTZ/translate.js",
			"ext/modules/character/XWTZ/voices.js",

			"ext/modules/character/JLBC/card.js",
			"ext/modules/character/JLBC/character.js",
			"ext/modules/character/JLBC/characterFilter.js",
			"ext/modules/character/JLBC/characterReplace.js",
			"ext/modules/character/JLBC/characterTitle.js",
			"ext/modules/character/JLBC/dynamicTranslate.js",
			"ext/modules/character/JLBC/index.js",
			"ext/modules/character/JLBC/intro.js",
			"ext/modules/character/JLBC/pinyin.js",
			"ext/modules/character/JLBC/skill.js",
			"ext/modules/character/JLBC/sort.js",
			"ext/modules/character/JLBC/translate.js",
			"ext/modules/character/JLBC/voices.js",

			"ext/modules/character/index.js",

			"ext/modules/introduce.index.js"

	],
};