import { lib, game, ui, get, ai, _status } from "../../../../../../noname.js";

const characters = {
	//魏
	"xjzh_sanguo_wenyang":{
		sex:"male",
		group:"wei",
		hp:4,
		skills:["xjzh_sanguo_pijian","xjzh_sanguo_zhirui","xjzh_sanguo_yongjue"],
		names:"文|鸯",
	},
	"xjzh_sanguo_zhangliao":{
		sex:"male",
		group:"wei",
		hp:3,
		skills:["xjzh_sanguo_zhiti","xjzh_sanguo_cuifengx"],
		names:"张|辽",
	},
	"xjzh_sanguo_xunyou":{
		sex:"male",
		group:"wei",
		hp:3,
		skills:["xjzh_sanguo_qice","xjzh_sanguo_zhiyu"],
		names:"荀|攸",
	},
	"xjzh_sanguo_xuzhu":{
		sex:"male",
		group:"wei",
		hp:4,
		skills:["xjzh_sanguo_luoyi","xjzh_sanguo_huchi"],
		names:"许|诸",
	},
	"xjzh_sanguo_guanlu":{
		sex:"male",
		group:"wei",
		hp:3,
		skills:["xjzh_sanguo_busuan"],
		names:"管|辂",
	},
	"xjzh_sanguo_caiyan":{
		sex:"male",
		group:"wei",
		hp:3,
		skills:["xjzh_sanguo_caiqing","xjzh_sanguo_zhishu","xjzh_sanguo_beige","xjzh_sanguo_guihan"],
		names:"蔡|琰",
	},
	"xjzh_sanguo_zhenfu":{
		sex:"male",
		group:"wei",
		hp:3,
		skills:["xjzh_sanguo_luoshen","xjzh_sanguo_qixian","xjzh_sanguo_qingguo"],
		names:"甄|宓",
	},
	"xjzh_sanguo_guojia":{
		sex:"male",
		group:"wei",
		hp:3,
		skills:["xjzh_sanguo_guimou","xjzh_sanguo_tianji","xjzh_sanguo_tianqi"],
		names:"郭|嘉",
	},
	"xjzh_sanguo_dianwei":{
		sex:"male",
		group:"wei",
		hp:6,
		skills:["xjzh_sanguo_elai","xjzh_sanguo_tiequ"],
		names:"典|韦",
	},
	"xjzh_sanguo_caocao":{
		sex:"male",
		group:"wei",
		hp:4,
		skills:["xjzh_sanguo_daizhao","xjzh_sanguo_guixin","xjzh_sanguo_feiying","xjzh_sanguo_batu"],
		names:"曹|操",
		isZhugong:true,
	},
	//蜀
	"xjzh_sanguo_yueying":{
		sex:"female",
		group:"shu",
		hp:3,
		skills:["xjzh_sanguo_qicai","xjzh_sanguo_jiqiao","xjzh_sanguo_jianqing"],
		names:"黄|月英",
	},
	"xjzh_sanguo_zhaoyun":{
		sex:"male",
		group:"shu",
		hp:2,
		skills:["xjzh_sanguo_juejing","xjzh_sanguo_longhun","xjzh_sanguo_peijian"],
		names:"赵|云",
		InitFilter:["noZhuHp"],
	},
	"xjzh_sanguo_weiyan":{
		sex:"male",
		group:"shu",
		hp:4,
		skills:["xjzh_sanguo_kuanggu","xjzh_sanguo_kuangxi","xjzh_sanguo_aogu"],
		names:"魏|延",
	},
	"xjzh_sanguo_kongming":{
		sex:"male",
		group:"shu",
		hp:4,
		skills:["xjzh_sanguo_duice","xjzh_sanguo_zhiji","xjzh_sanguo_bazhen"],
		names:"诸葛|亮",
	},
	"xjzh_sanguo_spkongming":{
		sex:"male",
		group:"shu",
		hp:3,
		skills:["xjzh_sanguo_guanxing","xjzh_sanguo_xinghun","xjzh_sanguo_qixing"],
		names:"诸葛|亮",
	},
	"xjzh_sanguo_huangzhong":{
		sex:"male",
		group:"shu",
		hp:4,
		skills:["xjzh_sanguo_liegong","xjzh_sanguo_chuzhen","xjzh_sanguo_zhujian"],
		names:"黄|忠",
	},
	"xjzh_sanguo_machao":{
		sex:"male",
		group:"shu",
		hp:2,
		maxHp:4,
		skills:["xjzh_sanguo_tieji","xjzh_sanguo_jieqiang","xjzh_sanguo_xiongbin"],
		names:"马|超",
	},
	"xjzh_sanguo_pangtong":{
		sex:"male",
		group:"shu",
		hp:3,
		skills:["xjzh_sanguo_liansuo","xjzh_sanguo_hengzhou","xjzh_sanguo_moulue"],
		names:"庞|统",
	},
	"xjzh_sanguo_zhangfei":{
		sex:"male",
		group:"shu",
		hp:3,
		skills:["xjzh_sanguo_shijiu","xjzh_sanguo_shayi","xjzh_sanguo_zhenhun"],
		names:"张|飞",
	},
	"xjzh_sanguo_guanyu":{
		sex:"male",
		group:"shu",
		hp:5,
		skills:["xjzh_sanguo_wusheng","xjzh_sanguo_hengdao","xjzh_sanguo_wushen"],
		names:"关|羽",
	},
	"xjzh_sanguo_liubei":{
		sex:"male",
		group:"shu",
		hp:5,
		skills:["xjzh_sanguo_longnu","nzry_jieying","xjzh_sanguo_jieyi"],
		names:"刘|备",
		isZhugong:true,
	},
	//吴
	"xjzh_sanguo_espsunce":{
		sex:"male",
		group:"wu",
		hp:3,
		skills:["xjzh_sanguo_zhawang","xjzh_sanguo_xingwu","xjzh_sanguo_jiang","xjzh_sanguo_hunzi"],
		names:"孙|策",
		isZhugong:true,
	},
	"xjzh_sanguo_sunquan":{
		sex:"male",
		group:"wu",
		hp:4,
		skills:["xjzh_sanguo_zhiheng","xjzh_sanguo_wuyun","xjzh_sanguo_jiuyuan"],
		names:"孙|权",
		isZhugong:true,
	},
	"xjzh_sanguo_ganning":{
		sex:"male",
		group:"wu",
		hp:4,
		skills:["xjzh_sanguo_youxia"],
		names:"甘|宁",
	},
	"xjzh_sanguo_daqiao":{
		sex:"female",
		group:"wu",
		hp:3,
		skills:["xjzh_sanguo_guose","xjzh_sanguo_wanrong","xjzh_sanguo_lixiang"],
		names:"null|null",
	},
	"xjzh_sanguo_xiaoqiao":{
		sex:"female",
		group:"wu",
		hp:3,
		skills:["xjzh_sanguo_tianxiang","xjzh_sanguo_emei","xjzh_sanguo_lixiang"],
		names:"null|null",
	},
	"xjzh_sanguo_sunhao":{
		sex:"male",
		group:"wu",
		hp:3,
		skills:["xjzh_sanguo_mingzheng","xjzh_sanguo_renjun"],
		names:"孙|皓",
		isZhugong:true,
	},
	"xjzh_sanguo_luxun":{
		sex:"male",
		group:"wu",
		hp:3,
		skills:["xjzh_sanguo_shishu","xjzh_sanguo_wulue","xjzh_sanguo_liantui"],
		names:"陆|逊",
	},
	"xjzh_sanguo_zhoutai":{
		sex:"male",
		group:"wu",
		hp:3,
		skills:["xjzh_sanguo_buqu","xjzh_sanguo_fenji"],
		names:"周|泰",
	},
	//群
	"xjzh_sanguo_dongzhuo":{
		sex:"male",
		group:"qun",
		hp:6,
		skills:["xjzh_sanguo_lanzheng","xjzh_sanguo_hengzheng","xjzh_sanguo_baolian","xjzh_sanguo_linnue"],
		names:"董|卓",
		isZhugong:true,
	},
	"xjzh_sanguo_zhangjiao":{
		sex:"male",
		group:"qun",
		hp:3,
		skills:["xjzh_sanguo_leihun","xjzh_sanguo_shendao","xjzh_sanguo_dianjie","xjzh_sanguo_huangtian"],
		names:"张|角",
		isZhugong:true,
	},
	"xjzh_sanguo_spzhangjiao":{
		sex:"male",
		group:"qun",
		hp:3,
		skills:["xjzh_sanguo_bujiao","xjzh_sanguo_taiping","xjzh_sanguo_fangshu"],
		names:"张|角",
		isZhugong:true,
	},
	"xjzh_sanguo_lvbu":{
		sex:"male",
		group:"qun",
		hp:4,
		skills:["xjzh_sanguo_mashu","xjzh_sanguo_shenji","xjzh_sanguo_feijiang","xjzh_sanguo_jiwu"],
		names:"吕|布",
		isZhugong:true,
	},
	"xjzh_sanguo_splvbu":{
		sex:"male",
		group:"qun",
		hp:4,
		skills:["mashu","xjzh_sanguo_shenji","xjzh_sanguo_shenwei"],
		names:"吕|布",
		isZhugong:true,
	},
	"xjzh_sanguo_huaxiong":{
		sex:"male",
		group:"qun",
		hp:19,
		skills:["xjzh_sanguo_shiyong","xjzh_sanguo_yaowu","xjzh_sanguo_yangwei"],
		names:"华|雄",
	},
	"xjzh_sanguo_nanhua":{
		sex:"male",
		group:"qun",
		hp:3,
		skills:["xjzh_sanguo_shouye","xjzh_sanguo_xianshou","xjzh_sanguo_lundao"],
		names:"null|null",
	},
	"xjzh_sanguo_simahui":{
		sex:"male",
		group:"qun",
		hp:3,
		skills:["xjzh_sanguo_jianjie","xjzh_sanguo_yinshi"],
		names:"司马|徽",
	},
	"xjzh_sanguo_huatuo":{
		sex:"male",
		group:"qun",
		hp:2,
		maxHp:3,
		skills:["xjzh_sanguo_shengxin","xjzh_sanguo_jishi","xjzh_sanguo_liangyi"],
		names:"华|佗",
	},
	"xjzh_sanguo_sphuatuo":{
		sex:"male",
		group:"qun",
		hp:3,
		skills:["xjzh_sanguo_xingyi","xjzh_sanguo_qingnang"],
		names:"华|佗",
	},
	"xjzh_sanguo_zuoci":{
		sex:"male",
		group:"qun",
		hp:3,
		skills:["xjzh_sanguo_daoshu","xjzh_sanguo_huanhua"],
		names:"左|慈",
	},
	"xjzh_sanguo_tongyuan":{
		sex:"male",
		group:"qun",
		hp:3,
		skills:["xjzh_sanguo_keluan","xjzh_sanguo_cuifeng","xjzh_sanguo_chaohuang"],
		names:"童|渊",
	},
	"xjzh_sanguo_zhangning":{
		sex:"female",
		group:"qun",
		hp:3,
		skills:["xjzh_sanguo_shanxi","xjzh_sanguo_leijix"],
		names:"张|宁",
	},
	"xjzh_sanguo_zhangrang":{
		sex:"male",
		group:"qun",
		hp:get.mode()=="identity"?Infinity:4,
		skills:["xjzh_sanguo_luanzheng","xjzh_sanguo_chanxian","xjzh_sanguo_shichong"],
		names:"张|让",
	},
	"xjzh_sanguo_bogui":{
		sex:"male",
		group:"qun",
		hp:3,
		skills:["xjzh_sanguo_baima","xjzh_sanguo_yicong","xjzh_sanguo_muma"],
		names:"公孙|瓒",
	},
	"xjzh_sanguo_diaochan":{
		sex:"male",
		group:"qun",
		hp:4,
		skills:["xjzh_sanguo_yuewu","xjzh_sanguo_yuehun"],
		names:"null|null",
	},
	"xjzh_sanguo_zhangbao":{
		sex:"male",
		group:"qun",
		hp:3,
		skills:["xjzh_sanguo_zhoufu","xjzh_sanguo_yingbin"],
		names:"张|宝",
	},
	"xjzh_sanguo_yuanshao":{
		sex:"male",
		group:"qun",
		hp:3,
		skills:["xjzh_sanguo_tanzhi","xjzh_sanguo_mingmen"],
		names:"袁|绍",
	},
	"xjzh_sanguo_yuji":{
		sex:"male",
		group:"qun",
		hp:3,
		skills:["xjzh_sanguo_guhuo","xjzh_sanguo_chanyuan"],
		names:"于|吉",
	},
	"xjzh_sanguo_zuoyou":{
		sex:"female",
		group:"qun",
		hp:3,
		skills:["xjzh_sanguo_tongxuan","xjzh_sanguo_youbian"],
		names:"左|幽",
	},
	//晋
	"xjzh_sanguo_zhongda":{
		sex:"male",
		group:"jin",
		hp:3,
		skills:["xjzh_sanguo_yinren","xjzh_sanguo_bolue","xjzh_sanguo_biantian"],
		names:"司马|懿",
		isZhugong:true,
	},
	"xjzh_sanguo_chunhua":{
		sex:"female",
		group:"jin",
		hp:3,
		maxHp:4,
		skills:["xjzh_sanguo_jueqing","xjzh_sanguo_shangshi","xjzh_sanguo_huishi"],
		names:"张|春华",
	},
	//神
	"xjzh_sanguo_espzhangjiao":{
		sex:"male",
		group:"shen",
		hp:4,
		skills:["xjzh_boss_dianxing"],
		names:"张|角",
		isUnseen:true,
		isAiForbidden:true,
	},
	"xjzh_sanguo_espzuoci":{
		sex:"male",
		group:"shen",
		hp:3,
		skills:["xjzh_sanguo_quling"],
		names:"左|慈",
		isUnseen:true,
		isAiForbidden:true,
	},
	"xjzh_sanguo_espliuxie":{
		sex:"male",
		group:"shen",
		hp:4,
		skills:["xjzh_sanguo_tiance","xjzh_sanguo_tianming","xjzh_sanguo_moubian","xjzh_sanguo_zhongxing"],
		names:"刘|协",
	},

};

for(let i in characters){
	if(!characters[i].trashBin) characters[i].trashBin=[];
	let array=["ext:仙家之魂/skin/yuanhua/"+i+".jpg","xjzh_die_audio"];
	if(lib.config.extension_仙家之魂_xjzh_lutoupifu) array.splice(0,1,"ext:仙家之魂/skin/lutou/"+i+".jpg");
	characters[i].trashBin.addArray(array);

	if(!characters[i].dieAudios) characters[i].dieAudios=[];
	characters[i].dieAudios.add("ext:仙家之魂/audio/die/"+i+".mp3");


	if(game.getExtensionConfig("仙家之魂","xjzhAchiStorage")&&game.getExtensionConfig("仙家之魂","xjzhAchiStorage").character&&game.getExtensionConfig("仙家之魂","xjzhAchiStorage").character.length){
		for(let name of game.getExtensionConfig("仙家之魂","xjzhAchiStorage").character){
			if(!characters[name]) console.log('未在仙武三国武将包找到该武将');
			else{
				characters[name].isAiForbidden=false;
				characters[name].isUnseen=false;
			}
		}
	}
}

export default characters;