const translates = {
	//美女如云
	"xjzh_meiren_linshuang":"林霜",
	"xjzh_meiren_gaoyu":"高雨",
	"xjzh_meiren_zhaoyushu":"赵玉姝",
	"xjzh_meiren_linjiasheng":"林嘉笙",
	"xjzh_meiren_wuyufeng":"吴玉凤",
	"xjzh_meiren_huangyuke":"黄毓珂",
	"xjzh_meiren_xiangwanru":"向婉茹",
	"xjzh_meiren_huangdanxue":"黄丹雪",

	"xjzh_meiren_juese":"绝色",
	"xjzh_meiren_juese_info":"出牌阶段限一次，你可以弃置一张黑色牌选择一名男性角色或弃置一张红色牌选择一名其他女性角色，然后执行以下规则：黑色，令其随机获得“弃置两张牌（不足则改为你摸两张牌）”或“失去所有技能直到其回合结束”；红色，令其随机获得“摸两张牌”或“回复一点体力（若其未受伤你可以再次发动该技能）”。",
	"xjzh_meiren_xiuya":"秀雅",
	"xjzh_meiren_xiuya_info":"锁定技，你的回合外，每当你需要打出或使用一张牌时，若牌顶堆的前三张有这张牌，你获得之",
	"xjzh_meiren_shumei":"淑美",
	"xjzh_meiren_shumei_info":"当你受到伤害后，你可以选择一项：1，选择一个目标令其随机获得一个技能并摸一张牌，2；令伤害来源弃置一张牌然后你摸3张牌。你可以重复此流程x-1次（x为你本回合受到伤害的次数）",
	"xjzh_meiren_ganling":"甘霖",
	"xjzh_meiren_ganling_info":"锁定技，你防止受到所有伤害且无法成为延时锦囊的目标；你的回合外，你无法失去体力和体力上限；你防止非正常阵亡。",
	"xjzh_meiren_miaofa":"妙法",
	"xjzh_meiren_miaofa_info":"锁定技，游戏开始及你的准备阶段开始时，你失去一点体力并摸一张牌，然后从未上场的<span style=\"color: blue\">〖仙家之魂〗</span>扩展武将中展示两个技能并选择获得一个技能，限定技，觉醒技，主公技等特殊技能除外",
	"xjzh_meiren_lunzhuan":"轮转",
	"xjzh_meiren_lunzhuan_info":"锁定技，你的手牌上限始终为你的体力上限<li>每局游戏限3次，当你阵亡前，若你的体力上限不小于2，你失去一点体力上限并恢复体力至1，然后弃置判定区的所有牌并摸手牌上限张牌<li>你失去牌有45%几率摸一张牌<li>你濒死时有40%几率恢复一点体力",
	"xjzh_meiren_jingzhuang":"镜装",
	"xjzh_meiren_jingzhuang_info":"锁定技，当你受到伤害前，你可以随机获得以下效果之一：<li>取消之并令其受到一点伤害<li>摸两张牌<li>受到伤害+1",
	"xjzh_meiren_chunxiao":"春宵",
	"xjzh_meiren_chunxiao_info":"锁定技，当你受到伤害后，伤害来源获得一个“春”标记，你获得春宵效果，你造成伤害有25%几率获得一点体力上限并摸一张牌（对有“春”标记的目标几率翻倍并令其弃置一张牌，然后移除标记），你对拥有“春”标记的目标造成伤害后失去春宵效果直到下次受到伤害",
	"xjzh_meiren_meihun":'魅魂',
	"xjzh_meiren_meihun_info":'锁定技，当你成为具有[伤害]标签的卡牌的目标后，你可以令一名其他角色交给你一张你声明的花色的手牌，若其没有则你观看其手牌然后弃置其中一张<li>其他角色每获得你一张牌时，须弃置一张牌',
	"xjzh_meiren_meihun2":"魅魂",
	"xjzh_meiren_tianzi":"天姿",
	"xjzh_meiren_tianzi_info":"锁定技，其他角色回合开始时，若其手牌大于你，你摸一张牌<li>你的准备阶段，若你的手牌为全场最多或之一，你可以选择:①失去一点体力;②你调整手牌数为你的体力值并摸体力上限张牌，若此时你的手牌为全场唯一最多，你跳过摸牌阶段）",
	"xjzh_meiren_tianzi2":"天姿",
	"xjzh_meiren_huoxin_control":'惑心',
	"xjzh_meiren_huoxin":'惑心',
	"xjzh_meiren_huoxin_info":'锁定技，出牌阶段限一次，你可以选择两个目标，然后令其拼点，若其没有手牌则摸可以一张牌，输家获得1个“魅惑”标记，然后你和赢家摸一张牌。拥有一个或更多“魅惑”的角色回合即将开始时，该角色移除其所有“魅惑”，此回合改为由你操控。',
	"xjzh_meiren_huizhi":"蕙质",
	"xjzh_meiren_huizhi_info":"锁定技，游戏开始后，你随机获得三张未加入游戏的武将牌称为“兰心”，并选择一张武将牌，你拥有该武将牌的所有技能且同时将性别和势力属性变成与该武将相同直到该武将牌被替换。你的每个准备阶段和结束阶段或受到伤害后，你可以选择一项：①弃置至多两张未展示的武将牌牌并重新获得等量武将牌，然后摸等量手牌；②更换所展示的武将牌或技能并摸一张牌。（你不可声明限定技、觉醒技、隐匿技、主公技等特殊技能）。",
	"xjzh_meiren_huizhi2":"蕙质",
	"xjzh_meiren_lanxin":"兰心",
	"xjzh_meiren_lanxin_info":"锁定技，你受到伤害或流失体力后，你获得等量新的武将牌。",
	"xjzh_meiren_gupan":"顾盼",
	"xjzh_meiren_gupan_info":"当你于回合外成为卡牌目标时，若你的“兰心”大于3且你已受伤，你可以弃置一张“兰心”然后摸x张牌(x为此“兰心”牌上的技能数量，当技能数量不大于2时，x等于2)。",
	"xjzh_meiren_rouqing":"柔情",
	"xjzh_meiren_rouqing_info":"锁定技，准备阶段开始时，若你的手牌只有一种花色，你可以依次亮出牌顶堆的牌，直到出现与你手牌同花色的牌，然后你获得这些牌。",
	"xjzh_meiren_jiaqi":"佳期",
	"xjzh_meiren_jiaqi_info":"当你受到伤害后，你可以弃置任意张不同花色的牌，令一名其他角色选择：弃置等量相同花色组成的牌；或翻面并获得你弃置的牌。",
	"xjzh_meiren_huimeng":"回梦",
	"xjzh_meiren_huimeng_info":"当你成为卡牌目标后，若你没有手牌，你可以观看牌顶堆x张牌并选择一种花色获得之，反之若你的卡牌数不为全场唯一最多，则你摸一张牌（x为你的体力值+1）",
	"xjzh_meiren_xianyou":"仙游",
	"xjzh_meiren_xianyou_info":"锁定技，当你发动〖<font color=red>回梦</font>〗之后，你获得一个“游”标记</br></br>当一名场上一名角色受到伤害后，你可以移除x个标记令其与伤害来源交换手牌，若你不为其，你摸一张牌（x你的手牌数）</br></br>当你成为卡牌目标时，你可以移除一个标记，并依据以下规则发动技能：<li>【杀】：你对其使用一张决斗，若你造成伤害，则该卡牌无效<li>【决斗】：你对其使用一张【杀】，若你未对其造成伤害，你弃置两张牌",
	"xjzh_meiren_xianyou1":"仙游",
	"xjzh_meiren_xianyou2":"仙游",
	"xjzh_meiren_xianyou3":"仙游",
	"xjzh_meiren_zhongqing":"钟情",
	"xjzh_meiren_zhongqing_info":"锁定技，游戏开始时，你指定一名角色为你的钟情对象；当其/你成为其他角色的卡牌目标时，该卡牌目标改为你/其，然后你与其各摸一张牌。",
	"xjzh_meiren_yiqing":"移情",
	"xjzh_meiren_yiqing_info":"当你成为其他女性角色/男性角色的非伤害/伤害卡牌的唯一目标时，你可以进行一次判定：♥目标转移给下家，♠目标转移给上家；若判定成功，你摸一张牌。",
	"xjzh_meiren_shangqing":"伤情",
	"xjzh_meiren_shangqing_info":"觉醒技，你的回合开始时，若你已至少发动6次〖钟情〗，你失去〖钟情〗，获得〖默情〗，然后你与一名其他角色交换体力值、体力上限。",
	"xjzh_meiren_moqing":"默情",
	"xjzh_meiren_moqing_info":"你无法成为所有指定角色为全部目标卡牌的目标；你受到伤害后，你可以与一名体力值不与你相等角色交换体力值，然后若其体力值大于你，你于当前回合结束后摸一张牌并开始一个额外的出牌阶段。",
	"xjzh_meiren_qingquan":"清泉",
	"xjzh_meiren_qingquan_info":"锁定技，当你回复体力后，你获得一点护甲，然后你令一名其他角色随机执行一项：①回复一点体力；②摸一张牌；③获得一点护甲。若你已觉醒，目标执行所有项且可选择任意名目标。",
	"xjzh_meiren_hanshuang":"寒霜",
	"xjzh_meiren_hanshuang_info":"觉醒技，当你阵亡时，你取消之并失去一点体力上限，将〖清泉〗中的“获得一点护甲”改为“获得两点护甲”，然后回复体力至1并获得技能〖凛冬〗。",
	"xjzh_meiren_lingdong":"凛冬",
	"xjzh_meiren_lingdong_info":"锁定技，场上除你之外的所有角色回复体力都会令你获得一点护甲；当你因抵挡伤害而护甲后，你将手牌补至体力上限。",

	//天命奇侠
	"xjzh_qixia_daxiongxiaomao":"大熊小猫",
	"xjzh_qixia_maybe":"昔日烈火",
	"xjzh_qixia_mumuxiao":"木木枭",

	"xjzh_qixia_qice":"奇策",
	"xjzh_qixia_qice_info":"其他角色摸牌后，若这些牌的类别不小于2，你可以观看并选择其中一种类别，令其弃置该类别的所有牌然后摸等量牌。",
	"xjzh_qixia_tianshu":"天书",
	"xjzh_qixia_tianshu_info":"锁定技，你的准备/结束阶段，你将一张《金庸群侠传》的武将牌写入天书，然后你视为拥有此武将牌上的技能；出牌阶段限一次，你可以获得天书上一张武将牌的一个技能，若如此做，你弃置该武将牌，然后获得牌堆点数和为这张武将牌上技能描述字数一致的任意张牌。",
	"xjzh_qixia_xiongmao":"熊猫",
	"xjzh_qixia_xiongmao_info":"出牌阶段限一次，你可以将你的武将原画调整为一名随机女性角色的原画，然后你将势力、性别、体力上限、体力值均调整为与其一致。",
	"xjzh_qixia_jiyuan":"急援",
	"xjzh_qixia_jiyuan_info":"当一名角色即将受到伤害时，你可以代替其受到伤害，若如此做，其摸两张牌；场上每有一名友方角色，你的回合开始时，你回复一点体力（至低为1），多余的回复转为摸牌（至低为1）",
	"xjzh_qixia_jibian":"机变",
	"xjzh_qixia_jibian_info":"当你受到伤害后，你摸x张点数为y的牌(x为你与伤害来源的体力差的绝对值，至低为1，y为体力和，至多为13)，然后令其技能描述中含有[伤害]的技能替换为〖仁德〗。",
	"xjzh_qixia_tubian":"图变",
	"xjzh_qixia_tubian_info":"出牌阶段、你受到伤害后限一次，你可以输入一名武将的武将名并展示3张武将名中包含你所输入的值的武将牌(至多5个汉字，若无对应汉字的武将牌或未输入，则改为随机展示3张武将牌)，并将一名角色武将图片改为你选择的武将图片，若其性别与你选择的武将性别不一致，你选择并令其失去当前武将牌上的一个技能，然后你选择令其获得你选择武将牌上的一个技能，否则其（或你为目标时）获得你选择的武将牌上的所有技能，若如此做，你随机切换你的武将性别。技能结算后，若你的武将性别为双，你获得一点体力上限，若你未改变性别，你回复一点体力并摸一张牌，否则你失去一点体力。",

};

export default translates;